server:
  port: 3081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: users
        uri: http://localhost:8081/
        predicates:
        - Path=/user/**
      - id: admin
        uri: http://localhost:8082/
        predicates:
        - Path=/admin/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true